version: "3.9"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blog
    env_file:
      - backend/.env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: uvicorn blog.api.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - minha_rede_app

  db:
    image: postgres:17.5
    restart: unless-stopped
    container_name: db
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede_app

  db_test:
    image: postgres:17.5
    restart: unless-stopped
    container_name: db_test
    environment:
      POSTGRES_DB: blog_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - minha_rede_app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - minha_rede_app

volumes:
  postgres_data:
  pgadmin_data:
  pgdata_test:

networks:
  minha_rede_app:
    driver: bridge
