version: "3.9"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
